### ISSUE TITLE
e

### ISSUE THREAD

**Issue by ForkAndSpoonIt** [Snowflake-Blooket-dude/Blooket-hack#11]
@Snowflake-Blooket-dude . u interested in a games site in the repo. i cant make hacks so istill wanna help

**Comment by ForkAndSpoonIt** [comment]
btw does this mean that 
bigguystevieb1 is legally allowed to copy u MIT License

Copyright (c) 2022 Blooekt-Dude

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**Comment by ForkAndSpoonIt** [comment]
@Hankypoo7  @Snowflake-Blooket-dude

**Comment by Snowflake-Blooket-dude** [comment]
yes im interested in a games site! Also Yes but no because I told him not to take my hacks and he did anyways!

**Comment by Snowflake-Blooket-dude** [comment]
@ForkAndSpoonIt

**Comment by ForkAndSpoonIt** [comment]
ok should i do it in this repo? Also, I know how to make a password to enter the site. should i add it? i need perms

**Comment by ForkAndSpoonIt** [comment]
@Snowflake-Blooket-dude

**Comment by Snowflake-Blooket-dude** [comment]
give me a sec

**Comment by Snowflake-Blooket-dude** [comment]
@ForkAndSpoonIt Im going to make a seperate repo for the games site just so it dosent get mixed up with the hacks and ill put a link in here to let people know that we have a games site?

**Comment by Snowflake-Blooket-dude** [comment]
Ill just make a basic repo and ill let you do it all becase I have no idea how to make a game websitei only know how to code hacks.


-Snowflake

**Comment by ForkAndSpoonIt** [comment]
ok! I already have a site (forkandspoonit.github.io) but ill start over

**Comment by Snowflake-Blooket-dude** [comment]
dont start over

**Comment by Snowflake-Blooket-dude** [comment]
wait your accually good at making a website

**Comment by ForkAndSpoonIt** [comment]
(its not a very good site) (it will take 5min to get better than it

**Comment by Snowflake-Blooket-dude** [comment]
if you wanna we can start over

**Comment by ForkAndSpoonIt** [comment]
ok

**Comment by Snowflake-Blooket-dude** [comment]
here ill make u a colllaberator in the new repo

**Comment by Snowflake-Blooket-dude** [comment]
ok I just sent you an inventation.


-Snowflake
